лаба 2 успешно работает
DailyPepper/AutoTesting pull request #3
Opened 2024-05-18 15:18 UTC by DailyPepper

Лаба 2 работает, все сделано 
![Uploading Снимок экрана 2024-05-18 в 18.16.33.png…]()

2024-05-18 15:19 UTC, DailyPepper commented
![Uploading Снимок экрана 2024-05-18 в 18.16.33.png…]()

2024-05-18 15:19 UTC, DailyPepper commented
![Uploading Снимок экрана 2024-05-18 в 18.16.33.png…]()

2024-05-19 18:41 UTC, gagashaggy requested changes
Отсутствует проверка, что текущий день недели выделен цветом

2024-05-19 18:44 UTC, gagashaggy commented
И кстати поле для поиска группы тоже почему-то не заполняется

2024-05-20 19:33 UTC, gagashaggy commented
В шаге 'Сравнивает выделенный день недели с сегодняшним' в блоке catch проглатывается ошибка, сообщение выводимое в консоль вводит в заблуждение. Если это убрать, то выясняется, что последняя проверка не проходит: assert.ok(weekDayColor.includes('background-color'), "День недели не выделен цветом"); потому что у проверяемого элемента отсутствует атрибут style:
```
      AssertionError [ERR_ASSERTION]: День недели не выделен цветом
      + expected - actual

      -false
      +true
```
Здесь не нужно проверять стили, в какой там цвет покрашено и т.п., достаточно просто проверять, что у нужного элемента присутствует класс schedule-day_today

2024-05-20 21:37 UTC, merged

2024-05-20 21:38 UTC, DailyPepper commented
Я немного намудрил с ветками, но в папке lab2 отображаются изменения